### ISSUE TITLE
Script fails when image URLs have the same suffix

### ISSUE THREAD

**Issue by tkaufmann** [artiomn/markdown_images_downloader#3]
I tend to share images publicy on my nextcloud. They get their own preview webpage on links like 

https://nextcloud/s/xj3DQpSJXgzsA2x

and can be downloaded/inserted into markdown files by appending '/preview'

https://nextcloud/s/xj3DQpSJXgzsA2x/preview

Unfortunately markdown_images_downloader will download all images as preview.ext, overwriting the same file again and again.

**Comment by artiomn** [comment]
Fixed.

**Comment by tkaufmann** [comment]
That's a nice solution, learned something for my own programming skills. Thanks a lot!
